const types = {
  UPDATE_FORM_FIELD: "UPDATE_FORM_FIELD",
  SET_FORM_FIELD_ERROR: "SET_FORM_FIELD_ERROR",
  SET_STEPS_DATA: "STEPS_DATA",
  SET_STEPS_PATHS: "STEPS_PATHS",
  UI_OPEN_MODAL: "uiOpenModal",
  UI_CLOSE_MODAL: "uiCloseModal",
  CLEAR_FORM: "CLEAR_FORM",
};
export default types;
